### ISSUE TITLE
Track and Remaining Track problems

### ISSUE THREAD

**Issue by hagensieker** [jscrane/lcd_lms#1] opened 2017-01-10 22:10 UTC
Grabbed this latest commit. Line 4 of LCD, lower right corner the track number and tracks remaining are reported correctly until the song is stopped or another service or song is streamed.  The track number and track remaining information then disappears.   Let me know the intended location for log files to grab for upload.

**Comment by hagensieker** [comment] 2017-01-13 11:13
![screen shot 2017-01-13 at 6 08 21 am](https://cloud.githubusercontent.com/assets/6775427/21928188/5b142764-d957-11e6-9db4-8e8af8932846.png)

**Comment by jscrane** [comment] 2017-01-13 11:15
I think you can simply attach files to comments.

**Comment by jscrane** [comment] 2017-01-17 19:13
closing this as duplicate of #2

**Closed as completed by jscrane** 2017-01-17 19:13 UTC
